<div id="content">
  <h1 id="page_title"><?= $vars['title'] ?></h1>
<div id="contact_form">
  <form method="POST" action="/submitForm">
    <input class="inputs" type="text" name="name" placeholder="name"/>
    <input class="inputs" type="text" name="website" placeholder="website"/>
    <input class="inputs" type="text" name="email" placeholder="email"/>
    
    <textarea class="inputs" rows="5" name="message" placeholder="message"></textarea>
    <input id="submit" type="submit" vaue="submit">
  </form>
</div>  
</div>

