<!doctype html>
<html>
  <head>
    <title><?= $this->title ?></title>
    <link type="text/css" rel="stylesheet" href="/css/style.css">
  </head>
  <body>  
  <header>
    <a href="/">
      <h1 id="logo">Nano MVC framework</h1>
    </a>  
    <nav>
      <ul id="nav_item">
         <li><a href="about">about</a></li>
         <li><a href="contact">contact</a></li>
      </ul>
    </nav>
  </header>
  
